### PR TITLE
Update reStore to handle new way of handling ejs params, and peg dependency versions for reference.

### LINKED ISSUE #28: "status not defined" at first contact
I'm not sure how I'm meant to use this, but here's my first attempt.

I followed the README instructions : installed with npm, copied your example basic server script from the README file, changed the path-to-files to a real path and changed the port to 7050. I then executed the script with node. 

I then tried to connect to the server from the favourite drinks example I'd installed in the starter-kit. 

The server blew up immediately with the following error : 

```
/home/phil/Documents/development/testing_frameworks/remote-storage/node_modules/restore/node_modules/ejs/lib/ejs.js:128
  throw err;
        ^
ReferenceError: ejs:1
 >> 1| <p class="status"><%= status %></p>
    2| <p class="message"><%= message %></p>
    3| 
    4| 

status is not defined
    at eval (eval at <anonymous> (/home/phil/Documents/development/testing_frameworks/remote-storage/node_modules/restore/node_modules/ejs/lib/ejs.js:302:12), <anonymous>:2:247)
    at /home/phil/Documents/development/testing_frameworks/remote-storage/node_modules/restore/node_modules/ejs/lib/ejs.js:328:17
    at Object.exports.render (/home/phil/Documents/development/testing_frameworks/remote-storage/node_modules/restore/node_modules/ejs/lib/ejs.js:177:13)
    at Controller.renderHTML (/home/phil/Documents/development/testing_frameworks/remote-storage/node_modules/restore/lib/controllers/base.js:111:17)
    at Controller.errorPage (/home/phil/Documents/development/testing_frameworks/remote-storage/node_modules/restore/lib/controllers/base.js:124:8)
    at Restore.dispatch (/home/phil/Documents/development/testing_frameworks/remote-storage/node_modules/restore/lib/restore.js:142:39)
    at IncomingMessage.<anonymous> (/home/phil/Documents/development/testing_frameworks/remote-storage/node_modules/restore/lib/restore.js:81:10)
    at IncomingMessage.EventEmitter.emit (events.js:92:17)
    at _stream_readable.js:910:16
    at process._tickDomainCallback (node.js:459:13)
```

### PR DESCRIPTION
**Pull request by silverbucket**
resolves #28

### CODE REVIEW

**Comment by skddc** [comment]
Tests are failing.

**Comment by silverbucket** [comment]
Would be cool if travis would notify the pull-requester when this happens.

**Comment by silverbucket** [comment]
This is npm weirdness:

```
npm ERR! Error: No compatible version found: ejs@'^2.0.8'

npm ERR! Valid install targets:

npm ERR! ["0.0.1","0.0.2","0.0.3","0.0.4","0.1.0","0.2.0","0.2.1","0.3.0","0.3.1","0.4.0","0.4.1","0.4.2","0.4.3","0.5.0","0.6.0","0.6.1","0.7.0","0.7.1","0.7.2","0.8.0","0.8.1","0.8.2","0.8.3","0.8.4","0.8.5","0.8.6","0.8.8","1.0.0","2.0.2","2.0.3","2.0.4","2.0.5","2.0.6","2.0.7","2.0.8"]
```

Clearly, `2.0.8` is listed, but somehow that doesn't work? Also it's only for the `node v0.8` branch. Not `v0.10` or `v0.11`

**Comment by skddc** [comment]
That one's outdated. You can remove it here: https://github.com/jcoglan/restore/blob/master/.travis.yml#L4-L6

**Comment by skddc** [comment]
Would be good if we can have 5apps master be a clean master branch with merged PRs, while @jcoglan is on break, so he can (hopefully) merge all of our fixes back to his repo when he comes back.

**Comment by jcoglan** [comment]
I've just merged your commits, thanks :)

**Pull request closed without merging**
